name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run test coverage
      run: go test $(go list ./... | grep -v example | grep -v pkged.go) -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
